 # Python script that performs the recapitation:
 # mamba activate msp
import tskit as tsk # installed via mamba 
import msprime #installed via pip bc mamba didnt work
import pyslim #installed via pip bc mamba didnt work
import numpy as np
import matplotlib.pyplot as plt
import argparse
import random
import sys

parser = argparse.ArgumentParser()
parser.add_argument("-i", "--input", help="input file name: tree sequence file")
parser.add_argument("-o", "--outpref", help="prefix for output file name")
parser.add_argument("--vcf", action="store_true",help="output VCF file")
parser.add_argument("--nspl", help = "number of samples to output to VCF")

args = parser.parse_args(args=None if sys.argv[1:] else ['--help'])

#infile = "../data/output_r10_s18082_j9820729.trees"
#pref = "output_r10_s18082_j9820729"
#infile = "../data/output_r1_s26128_j9856593.trees"
#pref = "output_r1_s26128_j9856593"
#infile = "../out9897319/output_r355_s10106_j9897319.trees"
#pref = "output_r355_s10106_j9897319"
infile = args.input
if args.outpref:
    pref = args.outpref
else:
    pref = infile+"_"

#infile = "../out9897319/output_r999_s9727_j9897319.trees" 

# Load the .trees file
ts = tsk.load(infile)

# Calculate tree heights, giving uncoalesced sites the maximum time
def tree_heights(ts):
    heights = np.zeros(ts.num_trees)
    for tree in ts.trees():
        children = tree.children(tree.root)
        real_root = tree.root if len(children) > 1 else children[0]
        heights[tree.index] = tree.time(real_root)
    return sum(heights)/len(heights)

# Recapitate!
recap = pyslim.recapitate(ts, ancestral_Ne=19300, recombination_rate=2.32e-6)#5e-7) # this was rescaled with Q=100
#recap.dump("../data/"+pref+"_recap.trees")
recsim = recap.simplify()
# mutation rate map setting mutation rate at site under SA (pos=5000) to zero, so that there is no overlap with neutral mutation
rates_exclmidsite = msprime.RateMap(position=[x for x in range(0,10001)], 
        rate=[1.39e-7 for x in range(0,4999)]+[0]+[1.39e-7 for x in range (5000,10000)])
mutated = msprime.sim_mutations(recsim, rate=rates_exclmidsite) # this was rescaled with Q=100

popnames=['Zambia', 'France', 'USA']
sfs=[]
nind=[]
allpopspls=[]
for p in range(mutated.num_populations-1): # excluded pop that was generated by recapitation
    pop=mutated.samples(p)
    nind.append(len(pop))
    tspop = mutated.simplify(samples=mutated.samples(p))
    if args.nspl:
        # subsample individuals from pop
        indspl = random.sample([x.id for x in tspop.individuals()], k=int(args.nspl))
    else:
        indspl = [x.id for x in tspop.individuals()]
    if args.vcf:
        # write to VCF file
        samplenames = [popnames[p]+"_"+str(x) for x in indspl]
        with open("../data/"+pref+"_"+popnames[p]+".vcf" , "w") as vcf:
            tspop.write_vcf(vcf, individuals=indspl, individual_names = samplenames)
    nodespl = list(np.concatenate([tspop.individual(x).nodes for x in indspl]))
    allpopspls += nodespl
    sfspop=tspop.allele_frequency_spectrum(sample_sets=[nodespl], windows=[0,2000,4000,6000,8000,10000], polarised=True, span_normalise=True)
    np.savetxt("../results/"+pref+"_"+popnames[p]+"_SFS.csv", sfspop, delimiter=",")

tsallspl = mutated.simplify(samples=list(set(allpopspls)))
print(tree_heights(tsallspl))
